### ISSUE TITLE
Blacklist for Topics

### ISSUE THREAD

**Issue by jeqo** [sysco-middleware/kafka-event-collector#17]
There could be some topics that are not interesting to be publishing events about (e.g. topic used by the collector, internal topics, and so on).

**Comment by NikitaZhevnitskiy** [comment]
Its obviously: 
1. Topic from collector config
2. Internal topics. Offer changes [here](https://github.com/sysco-middleware/kafka-event-collector/blob/ca1fdb3880bfa271f0322744cdad764efe561faa/src/main/scala/no/sysco/middleware/kafka/event/collector/internal/EventRepository.scala#L67)

```scala
  def handleDescribeTopic(describeTopic: DescribeTopic): Unit = {
    log.info("Handling describe topic {} command.", describeTopic.name)
    val thisSender: ActorRef = sender()
    adminClient.describeTopics(List(describeTopic.name).asJava)
      .all()
      .thenApply(topicsAndDescription => {
        val topicDescribed = topicsAndDescription.get(describeTopic.name)
        if (!topicDescribed.isInternal) {
          thisSender !
            TopicDescribed(
              describeTopic.name,
              Parser.fromKafka(topicDescribed))
        }
      })
  }
```

**Comment by jeqo** [comment]
Agree that it has to be configurable, but it should be on the `TopicManager` actor instead, as it is it where events are produced.

**Comment by jeqo** [comment]
Internal topics filtering is supported now by #18

**Comment by jeqo** [comment]
Completed by #19
